---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb
  namespace: devops-training
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size as per your requirement
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: db
  name: db
  namespace: devops-training
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: package_db
      ports:
        - containerPort: 3306
      resources:
        limits:
          cpu: '1'
          memory: 512Mi
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqldb
  volumes:
    - name: mysqldb
      persistentVolumeClaim:
        claimName: mysqldb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops-training
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: pun-api
        image: ghcr.io/frngrit/package-deliver/backend:dac295f7516df38506b5c1367e3db4c2623b6a2d
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        ports:
        - containerPort: 80
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api.service.port
        - name: DATABASE_HOST
          value: db
      imagePullSecrets:
        - name: frngrit-github
