apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: devops-training
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: api
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: devops-training
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: db
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: devops-training
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend
  type: LoadBalancer

---
